### ISSUE TITLE
Reloading the window breaks the fix.

### ISSUE THREAD

**Issue by 23phy** [toonvanvr/electron-transparency-mouse-fix#1]
Hello,
First of all, great job, it's a clever fix. My issue is the following:
### Steps to reproduce
  - run `npm run demo`
  - use `Ctrl+R` to reload the window, or use it in DevTools
  - TMF no longer works here, as the mouse is always off

### Expected behavior
The whitelist elements should still be able to receive events even after the window has been 

### A gif showing the process
![gif](https://user-images.githubusercontent.com/11774416/47385959-28e1bb00-d714-11e8-89ea-fc97c4db1047.gif)

**Comment by toonvanvr** [comment]
This indeed is an irritating bug when you're refreshing the page while developing. I'll look into it.

About the clever fix: I realized it's not so clever.. I forgot about the [pointer-events](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) CSS rule which makes blacklisting/whitelisting obsolete. Expect support for pointer-events in version 0.1.0, and if this bug is fixable, it'll be version 0.1.1.

**Comment by toonvanvr** [comment]
electron/electron#15376

I've posted an issue in the official electron repository. Let's hope they know a solution

**Comment by toonvanvr** [comment]
The fixPointerEvents workaround is applied by default in v1.0.0-beta.
- Windows: after a reload
- Linux: always
